name: GenerateCoverageReportWithAction Dev Workflow

on:
  push:
    branches:
      - develop
      - "feature_*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["5.0.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --collect:"XPlat Code Coverage"
      - name: Generate code coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.10
        with:
          reports: "./test/TestResults/*/*.xml"
          targetdir: "./test/TestResults/CoverageReport"
          reporttypes: "HtmlInline"
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: CoverageReport
          path: "./test/TestResults/CoverageReport"
