name: GenerateCoverageReportWithAction Dev Workflow

on:
  push:
    branches: [develop, feature/*, fix/*, improve/*]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --results-directory:"test/TestResults" --collect:"XPlat Code Coverage"
      - name: Generate code coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.9
        with:
          reports: "./test/TestResults/*/*.xml"
          targetdir: "./test/TestResults/CoverageReport"
          reporttypes: "HtmlInline"
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: CoverageReport
          path: "./test/TestResults/CoverageReport"
          retention-days: 7
